title: SmartFractyl's Personal Site
description: A less than decent Programmer with a Passion For Java, Science, Technology, C#, and Video Games
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
